//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.2.2+11a412c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "domainConfigurationTab"
	/// <summary>Domain Configuration Tab</summary>
	public partial interface IDomainConfigurationTab : IPublishedElement
	{
		/// <summary>Side Panel Left Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigAsideLeftWidth { get; }

		/// <summary>Side Panel Right Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigAsideRightWidth { get; }

		/// <summary>Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCardDateFormat { get; }

		/// <summary>Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCardTimeFormat { get; }

		/// <summary>Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigCategoryCache { get; }

		/// <summary>Default Aside Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ConfigDefaultAsideBackgroundColor { get; }

		/// <summary>Default Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultAsideBorderColor { get; }

		/// <summary>Default Aside Border Edges</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		global::Protenacity.Cake.Web.Core.Property.EditorBorderEdges ConfigDefaultAsideBorderEdges { get; }

		/// <summary>Missing Image Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultImageMissingColor { get; }

		/// <summary>Image Quality</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigImageQuality { get; }

		/// <summary>Custom Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigOpeningTimesCustomTimeFormat { get; }

		/// <summary>Maximum Allowed Pages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigPageMaximum { get; }

		/// <summary>Default Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigPageSizeDefault { get; }

		/// <summary>Maximum Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigPageSizeMaximum { get; }

		/// <summary>Fuzziness</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchFuzziness { get; }

		/// <summary>H1 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH1Boost { get; }

		/// <summary>H2 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH2Boost { get; }

		/// <summary>H3 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH3Boost { get; }

		/// <summary>H4 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH4Boost { get; }

		/// <summary>H5 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH5Boost { get; }

		/// <summary>H6 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchH6Boost { get; }

		/// <summary>Implement Fuzzy Results </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchImplementFuzzyResults { get; }

		/// <summary>Keywords Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchKeywordsBoost { get; }

		/// <summary>Promoted Search Terms Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		int ConfigSearchPromotedSearchTermsBoost { get; }

		/// <summary>SeoPriorities</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigSearchSeoPriorities { get; }
	}

	/// <summary>Domain Configuration Tab</summary>
	[PublishedModel("domainConfigurationTab")]
	public partial class DomainConfigurationTab : PublishedElementModel, IDomainConfigurationTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const string ModelTypeAlias = "domainConfigurationTab";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<DomainConfigurationTab, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public DomainConfigurationTab(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Side Panel Left Width: Pick a number between 1 and 12. Each consecutive number makes the side panel 8% wider. 1 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}1{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}11{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.  3 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}3{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}9{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configAsideLeftWidth")]
		public virtual int ConfigAsideLeftWidth => GetConfigAsideLeftWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Side Panel Left Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigAsideLeftWidth(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configAsideLeftWidth");

		///<summary>
		/// Side Panel Right Width: Pick a number between 1 and 12. Each consecutive number makes the side panel 8% wider. 2 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}2{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}10{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.  4 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}4{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}8{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configAsideRightWidth")]
		public virtual int ConfigAsideRightWidth => GetConfigAsideRightWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Side Panel Right Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigAsideRightWidth(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configAsideRightWidth");

		///<summary>
		/// Date Format: Date format used on Cards to display Date. Formats include dd/MM/yyyy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCardDateFormat")]
		public virtual string ConfigCardDateFormat => GetConfigCardDateFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCardDateFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCardDateFormat");

		///<summary>
		/// Time Format: Time format used on Cards to display Time. Formats include HH:mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCardTimeFormat")]
		public virtual string ConfigCardTimeFormat => GetConfigCardTimeFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCardTimeFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCardTimeFormat");

		///<summary>
		/// Default Cache Length: How long, in minutes, to cache Category information when reading them. The cache uses Examine's Editor Index to collect data.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configCategoryCache")]
		public virtual int ConfigCategoryCache => GetConfigCategoryCache(this, _publishedValueFallback);

		/// <summary>Static getter for Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigCategoryCache(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configCategoryCache");

		///<summary>
		/// Default Aside Background: Default background used for side panels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultAsideBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ConfigDefaultAsideBackgroundColor => GetConfigDefaultAsideBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Default Aside Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetConfigDefaultAsideBackgroundColor(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "configDefaultAsideBackgroundColor");

		///<summary>
		/// Default Border Color: Default color shown around side panels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultAsideBorderColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultAsideBorderColor => GetConfigDefaultAsideBorderColor(this, _publishedValueFallback);

		/// <summary>Static getter for Default Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetConfigDefaultAsideBorderColor(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "configDefaultAsideBorderColor");

		///<summary>
		/// Default Aside Border Edges: Default edges that are shown around the side panel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configDefaultAsideBorderEdges")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorBorderEdges ConfigDefaultAsideBorderEdges => GetConfigDefaultAsideBorderEdges(this, _publishedValueFallback);

		/// <summary>Static getter for Default Aside Border Edges</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static global::Protenacity.Cake.Web.Core.Property.EditorBorderEdges GetConfigDefaultAsideBorderEdges(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Protenacity.Cake.Web.Core.Property.EditorBorderEdges>(publishedValueFallback, "configDefaultAsideBorderEdges");

		///<summary>
		/// Missing Image Background Color: What col,our to use when an image is missing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultImageMissingColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultImageMissingColor => GetConfigDefaultImageMissingColor(this, _publishedValueFallback);

		/// <summary>Static getter for Missing Image Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetConfigDefaultImageMissingColor(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "configDefaultImageMissingColor");

		///<summary>
		/// Image Quality: Select number between 1 to 100. 1 = Awful images but fast. 100 = Perfect images, but slow.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configImageQuality")]
		public virtual int ConfigImageQuality => GetConfigImageQuality(this, _publishedValueFallback);

		/// <summary>Static getter for Image Quality</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigImageQuality(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configImageQuality");

		///<summary>
		/// Custom Time Format: Allows custom time formatitng. See {a href="https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings"}Custom date and time format{/a} for details
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configOpeningTimesCustomTimeFormat")]
		public virtual string ConfigOpeningTimesCustomTimeFormat => GetConfigOpeningTimesCustomTimeFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Custom Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigOpeningTimesCustomTimeFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configOpeningTimesCustomTimeFormat");

		///<summary>
		/// Maximum Allowed Pages: Maximum allowed pages of results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configPageMaximum")]
		public virtual int ConfigPageMaximum => GetConfigPageMaximum(this, _publishedValueFallback);

		/// <summary>Static getter for Maximum Allowed Pages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigPageMaximum(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageMaximum");

		///<summary>
		/// Default Page Size: Default Page Size of search results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configPageSizeDefault")]
		public virtual int ConfigPageSizeDefault => GetConfigPageSizeDefault(this, _publishedValueFallback);

		/// <summary>Static getter for Default Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigPageSizeDefault(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageSizeDefault");

		///<summary>
		/// Maximum Page Size: Maximum allowed size of a page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configPageSizeMaximum")]
		public virtual int ConfigPageSizeMaximum => GetConfigPageSizeMaximum(this, _publishedValueFallback);

		/// <summary>Static getter for Maximum Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigPageSizeMaximum(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageSizeMaximum");

		///<summary>
		/// Fuzziness: Required similarity between search query and matching results.  90 = Close matching only, 1 or 2 characters difference. 50 = Only half the characters are required to match.   Lower the value more matches but slower the search takes to execute. If value is too low, search query will match everything. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchFuzziness")]
		public virtual int ConfigSearchFuzziness => GetConfigSearchFuzziness(this, _publishedValueFallback);

		/// <summary>Static getter for Fuzziness</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchFuzziness(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchFuzziness");

		///<summary>
		/// H1 Boost: How important is H1 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH1Boost")]
		public virtual int ConfigSearchH1Boost => GetConfigSearchH1Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H1 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH1Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH1Boost");

		///<summary>
		/// H2 Boost: How important is H2 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH2Boost")]
		public virtual int ConfigSearchH2Boost => GetConfigSearchH2Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H2 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH2Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH2Boost");

		///<summary>
		/// H3 Boost: How important is H3 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH3Boost")]
		public virtual int ConfigSearchH3Boost => GetConfigSearchH3Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H3 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH3Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH3Boost");

		///<summary>
		/// H4 Boost: How important is H4 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH4Boost")]
		public virtual int ConfigSearchH4Boost => GetConfigSearchH4Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H4 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH4Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH4Boost");

		///<summary>
		/// H5 Boost: How important is H5 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH5Boost")]
		public virtual int ConfigSearchH5Boost => GetConfigSearchH5Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H5 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH5Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH5Boost");

		///<summary>
		/// H6 Boost: How important is H6 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchH6Boost")]
		public virtual int ConfigSearchH6Boost => GetConfigSearchH6Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H6 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchH6Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH6Boost");

		///<summary>
		/// Implement Fuzzy Results : Implement Fuzzy matching on query when results from exact matching returns less than this value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchImplementFuzzyResults")]
		public virtual int ConfigSearchImplementFuzzyResults => GetConfigSearchImplementFuzzyResults(this, _publishedValueFallback);

		/// <summary>Static getter for Implement Fuzzy Results </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchImplementFuzzyResults(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchImplementFuzzyResults");

		///<summary>
		/// Keywords Boost: How important is Keywords on Seo Tab compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchKeywordsBoost")]
		public virtual int ConfigSearchKeywordsBoost => GetConfigSearchKeywordsBoost(this, _publishedValueFallback);

		/// <summary>Static getter for Keywords Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchKeywordsBoost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchKeywordsBoost");

		///<summary>
		/// Promoted Search Terms Boost: How important is Promoted Search Terms on Seo Tab compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("configSearchPromotedSearchTermsBoost")]
		public virtual int ConfigSearchPromotedSearchTermsBoost => GetConfigSearchPromotedSearchTermsBoost(this, _publishedValueFallback);

		/// <summary>Static getter for Promoted Search Terms Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static int GetConfigSearchPromotedSearchTermsBoost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchPromotedSearchTermsBoost");

		///<summary>
		/// SeoPriorities: How important is each of the values of a webpage's SeoPriority starting from 10 to 0. Rate using comma separated values.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configSearchSeoPriorities")]
		public virtual string ConfigSearchSeoPriorities => GetConfigSearchSeoPriorities(this, _publishedValueFallback);

		/// <summary>Static getter for SeoPriorities</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigSearchSeoPriorities(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configSearchSeoPriorities");
	}
}
