//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "domainConfigurationTab"
	/// <summary>Domain Configuration Tab</summary>
	public partial interface IDomainConfigurationTab : IPublishedElement
	{
		/// <summary>Side Panel Left Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigAsideLeftWidth { get; }

		/// <summary>Side Panel Right Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigAsideRightWidth { get; }

		/// <summary>Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCardDateFormat { get; }

		/// <summary>Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCardTimeFormat { get; }

		/// <summary>Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigCategoryCache { get; }

		/// <summary>Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCoronerDateFormat { get; }

		/// <summary>Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigCoronerTimeFormat { get; }

		/// <summary>Default Aside Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ConfigDefaultAsideBackground { get; }

		/// <summary>Default Aside Border Edges</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::System.Collections.Generic.IEnumerable<string> ConfigDefaultAsideBorderEdges { get; }

		/// <summary>Missing Image Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultImageMissingColor { get; }

		/// <summary>From Email </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigFormFromEmail { get; }

		/// <summary>Image Quality</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigImageQuality { get; }

		/// <summary>Custom Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigOpeningTimesCustomTimeFormat { get; }

		/// <summary>Maximum Allowed Pages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigPageMaximum { get; }

		/// <summary>Default Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigPageSizeDefault { get; }

		/// <summary>Maximum Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigPageSizeMaximum { get; }

		/// <summary>Review Email Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ConfigReviewEmailBody { get; }

		/// <summary>Review Email Frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::System.Collections.Generic.IEnumerable<string> ConfigReviewEmailFrequency { get; }

		/// <summary>Review From Email</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigReviewEmailFrom { get; }

		/// <summary>Review Email Subject</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigReviewEmailSubject { get; }

		/// <summary>Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigRssFeedReaderCache { get; }

		/// <summary>Fuzziness</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchFuzziness { get; }

		/// <summary>H1 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH1Boost { get; }

		/// <summary>H2 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH2Boost { get; }

		/// <summary>H3 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH3Boost { get; }

		/// <summary>H4 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH4Boost { get; }

		/// <summary>H5 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH5Boost { get; }

		/// <summary>H6 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchH6Boost { get; }

		/// <summary>Implement Fuzzy Results </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchImplementFuzzyResults { get; }

		/// <summary>Keywords Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchKeywordsBoost { get; }

		/// <summary>Promoted Search Terms Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigSearchPromotedSearchTermsBoost { get; }

		/// <summary>SeoPriorities</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigSearchSeoPriorities { get; }

		/// <summary>Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigTheme { get; }

		/// <summary>Cache Length For Form Entries</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int ConfigUmbracoFormCacheLength { get; }

		/// <summary>Select Form Entries Message Field</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigUmbracoFormFieldMessage { get; }

		/// <summary>Select Form Entries Field Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigUmbracoFormFieldName { get; }

		/// <summary>Default Select Form Entries Field Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ConfigUmbracoFormFieldNameDefault { get; }
	}

	/// <summary>Domain Configuration Tab</summary>
	[PublishedModel("domainConfigurationTab")]
	public partial class DomainConfigurationTab : PublishedElementModel, IDomainConfigurationTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "domainConfigurationTab";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<DomainConfigurationTab, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public DomainConfigurationTab(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Side Panel Left Width: Pick a number between 1 and 12. Each consecutive number makes the side panel 8% wider. 1 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}1{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}11{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.  3 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}3{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}9{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configAsideLeftWidth")]
		public virtual int ConfigAsideLeftWidth => GetConfigAsideLeftWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Side Panel Left Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigAsideLeftWidth(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configAsideLeftWidth");

		///<summary>
		/// Side Panel Right Width: Pick a number between 1 and 12. Each consecutive number makes the side panel 8% wider. 2 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}2{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}10{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.  4 = side panel takes up {span style="font-size: 70%; vertical-align: 0.7ex;"}4{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} of the page leaving {span style="font-size: 70%; vertical-align: 0.7ex;"}8{/span}&frasl;{span style="font-size: 70%; vertical-align: -0.3ex;"}12{/span}{sup}th{/sup} for main content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configAsideRightWidth")]
		public virtual int ConfigAsideRightWidth => GetConfigAsideRightWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Side Panel Right Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigAsideRightWidth(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configAsideRightWidth");

		///<summary>
		/// Date Format: Date format used on Cards to display Date. Formats include dd/MM/yyyy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCardDateFormat")]
		public virtual string ConfigCardDateFormat => GetConfigCardDateFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCardDateFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCardDateFormat");

		///<summary>
		/// Time Format: Time format used on Cards to display Time. Formats include HH:mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCardTimeFormat")]
		public virtual string ConfigCardTimeFormat => GetConfigCardTimeFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCardTimeFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCardTimeFormat");

		///<summary>
		/// Default Cache Length: How long, in minutes, to cache Category information when reading them. The cache uses Examine's Editor Index to collect data.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configCategoryCache")]
		public virtual int ConfigCategoryCache => GetConfigCategoryCache(this, _publishedValueFallback);

		/// <summary>Static getter for Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigCategoryCache(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configCategoryCache");

		///<summary>
		/// Date Format: Date format used to display Coroner dates. Formats include dd/MM/yyyy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCoronerDateFormat")]
		public virtual string ConfigCoronerDateFormat => GetConfigCoronerDateFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Date Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCoronerDateFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCoronerDateFormat");

		///<summary>
		/// Time Format: Time format used to display Coroner times. Formats include HH:mm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configCoronerTimeFormat")]
		public virtual string ConfigCoronerTimeFormat => GetConfigCoronerTimeFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigCoronerTimeFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configCoronerTimeFormat");

		///<summary>
		/// Default Aside Background: Default background used for side panels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultAsideBackground")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ConfigDefaultAsideBackground => GetConfigDefaultAsideBackground(this, _publishedValueFallback);

		/// <summary>Static getter for Default Aside Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetConfigDefaultAsideBackground(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "configDefaultAsideBackground");

		///<summary>
		/// Default Aside Border Edges: Default edges that are shown around the side panel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultAsideBorderEdges")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ConfigDefaultAsideBorderEdges => GetConfigDefaultAsideBorderEdges(this, _publishedValueFallback);

		/// <summary>Static getter for Default Aside Border Edges</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::System.Collections.Generic.IEnumerable<string> GetConfigDefaultAsideBorderEdges(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Collections.Generic.IEnumerable<string>>(publishedValueFallback, "configDefaultAsideBorderEdges");

		///<summary>
		/// Missing Image Background Color: What col,our to use when an image is missing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configDefaultImageMissingColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor ConfigDefaultImageMissingColor => GetConfigDefaultImageMissingColor(this, _publishedValueFallback);

		/// <summary>Static getter for Missing Image Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetConfigDefaultImageMissingColor(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "configDefaultImageMissingColor");

		///<summary>
		/// From Email : When sending emails as part of submit workflow, who to send the email from
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configFormFromEmail")]
		public virtual string ConfigFormFromEmail => GetConfigFormFromEmail(this, _publishedValueFallback);

		/// <summary>Static getter for From Email </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigFormFromEmail(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configFormFromEmail");

		///<summary>
		/// Image Quality: Select number between 1 to 100. 1 = Awful images but fast. 100 = Perfect images, but slow.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configImageQuality")]
		public virtual int ConfigImageQuality => GetConfigImageQuality(this, _publishedValueFallback);

		/// <summary>Static getter for Image Quality</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigImageQuality(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configImageQuality");

		///<summary>
		/// Custom Time Format: Allows custom time formatitng. See {a href="https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings"}Custom date and time format{/a} for details
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configOpeningTimesCustomTimeFormat")]
		public virtual string ConfigOpeningTimesCustomTimeFormat => GetConfigOpeningTimesCustomTimeFormat(this, _publishedValueFallback);

		/// <summary>Static getter for Custom Time Format</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigOpeningTimesCustomTimeFormat(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configOpeningTimesCustomTimeFormat");

		///<summary>
		/// Maximum Allowed Pages: Maximum allowed pages of results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configPageMaximum")]
		public virtual int ConfigPageMaximum => GetConfigPageMaximum(this, _publishedValueFallback);

		/// <summary>Static getter for Maximum Allowed Pages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigPageMaximum(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageMaximum");

		///<summary>
		/// Default Page Size: Default Page Size of search results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configPageSizeDefault")]
		public virtual int ConfigPageSizeDefault => GetConfigPageSizeDefault(this, _publishedValueFallback);

		/// <summary>Static getter for Default Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigPageSizeDefault(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageSizeDefault");

		///<summary>
		/// Maximum Page Size: Maximum allowed size of a page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configPageSizeMaximum")]
		public virtual int ConfigPageSizeMaximum => GetConfigPageSizeMaximum(this, _publishedValueFallback);

		/// <summary>Static getter for Maximum Page Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigPageSizeMaximum(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configPageSizeMaximum");

		///<summary>
		/// Review Email Body: Email body for review content email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configReviewEmailBody")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ConfigReviewEmailBody => GetConfigReviewEmailBody(this, _publishedValueFallback);

		/// <summary>Static getter for Review Email Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetConfigReviewEmailBody(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "configReviewEmailBody");

		///<summary>
		/// Review Email Frequency: Which days of the week would you like to send review content emails
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configReviewEmailFrequency")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ConfigReviewEmailFrequency => GetConfigReviewEmailFrequency(this, _publishedValueFallback);

		/// <summary>Static getter for Review Email Frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::System.Collections.Generic.IEnumerable<string> GetConfigReviewEmailFrequency(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Collections.Generic.IEnumerable<string>>(publishedValueFallback, "configReviewEmailFrequency");

		///<summary>
		/// Review From Email: Which email address should we use to send review emails from
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configReviewEmailFrom")]
		public virtual string ConfigReviewEmailFrom => GetConfigReviewEmailFrom(this, _publishedValueFallback);

		/// <summary>Static getter for Review From Email</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigReviewEmailFrom(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configReviewEmailFrom");

		///<summary>
		/// Review Email Subject: Subject element for emails sent out when content requires review
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configReviewEmailSubject")]
		public virtual string ConfigReviewEmailSubject => GetConfigReviewEmailSubject(this, _publishedValueFallback);

		/// <summary>Static getter for Review Email Subject</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigReviewEmailSubject(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configReviewEmailSubject");

		///<summary>
		/// Default Cache Length: How long, in minutes, to cache Rss Feed when reading them, if the Rss Feed itself doesn't broadcast its cache rate/TTL.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configRssFeedReaderCache")]
		public virtual int ConfigRssFeedReaderCache => GetConfigRssFeedReaderCache(this, _publishedValueFallback);

		/// <summary>Static getter for Default Cache Length</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigRssFeedReaderCache(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configRssFeedReaderCache");

		///<summary>
		/// Fuzziness: Required similarity between search query and matching results.  90 = Close matching only, 1 or 2 characters difference. 50 = Only half the characters are required to match.   Lower the value more matches but slower the search takes to execute. If value is too low, search query will match everything. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchFuzziness")]
		public virtual int ConfigSearchFuzziness => GetConfigSearchFuzziness(this, _publishedValueFallback);

		/// <summary>Static getter for Fuzziness</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchFuzziness(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchFuzziness");

		///<summary>
		/// H1 Boost: How important is H1 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH1Boost")]
		public virtual int ConfigSearchH1Boost => GetConfigSearchH1Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H1 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH1Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH1Boost");

		///<summary>
		/// H2 Boost: How important is H2 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH2Boost")]
		public virtual int ConfigSearchH2Boost => GetConfigSearchH2Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H2 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH2Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH2Boost");

		///<summary>
		/// H3 Boost: How important is H3 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH3Boost")]
		public virtual int ConfigSearchH3Boost => GetConfigSearchH3Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H3 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH3Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH3Boost");

		///<summary>
		/// H4 Boost: How important is H4 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH4Boost")]
		public virtual int ConfigSearchH4Boost => GetConfigSearchH4Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H4 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH4Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH4Boost");

		///<summary>
		/// H5 Boost: How important is H5 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH5Boost")]
		public virtual int ConfigSearchH5Boost => GetConfigSearchH5Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H5 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH5Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH5Boost");

		///<summary>
		/// H6 Boost: How important is H6 content compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchH6Boost")]
		public virtual int ConfigSearchH6Boost => GetConfigSearchH6Boost(this, _publishedValueFallback);

		/// <summary>Static getter for H6 Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchH6Boost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchH6Boost");

		///<summary>
		/// Implement Fuzzy Results : Implement Fuzzy matching on query when results from exact matching returns less than this value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchImplementFuzzyResults")]
		public virtual int ConfigSearchImplementFuzzyResults => GetConfigSearchImplementFuzzyResults(this, _publishedValueFallback);

		/// <summary>Static getter for Implement Fuzzy Results </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchImplementFuzzyResults(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchImplementFuzzyResults");

		///<summary>
		/// Keywords Boost: How important is Keywords on Seo Tab compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchKeywordsBoost")]
		public virtual int ConfigSearchKeywordsBoost => GetConfigSearchKeywordsBoost(this, _publishedValueFallback);

		/// <summary>Static getter for Keywords Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchKeywordsBoost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchKeywordsBoost");

		///<summary>
		/// Promoted Search Terms Boost: How important is Promoted Search Terms on Seo Tab compared to other content.  10 = Ten times more important than other content. 1 = Same as other content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configSearchPromotedSearchTermsBoost")]
		public virtual int ConfigSearchPromotedSearchTermsBoost => GetConfigSearchPromotedSearchTermsBoost(this, _publishedValueFallback);

		/// <summary>Static getter for Promoted Search Terms Boost</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigSearchPromotedSearchTermsBoost(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configSearchPromotedSearchTermsBoost");

		///<summary>
		/// SeoPriorities: How important is each of the values of a webpage's SeoPriority starting from 10 to 0. Rate using comma separated values.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configSearchSeoPriorities")]
		public virtual string ConfigSearchSeoPriorities => GetConfigSearchSeoPriorities(this, _publishedValueFallback);

		/// <summary>Static getter for SeoPriorities</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigSearchSeoPriorities(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configSearchSeoPriorities");

		///<summary>
		/// Name: Actual css folder where themes is stored. {i}wwwroot/style/themes{/i} Folder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configTheme")]
		public virtual string ConfigTheme => GetConfigTheme(this, _publishedValueFallback);

		/// <summary>Static getter for Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigTheme(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configTheme");

		///<summary>
		/// Cache Length For Form Entries: How long in minutes should we cache Umbraco Form Results when displayed on front end. As each call is a hit on the database, its best to cache for as long as possible.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("configUmbracoFormCacheLength")]
		public virtual int ConfigUmbracoFormCacheLength => GetConfigUmbracoFormCacheLength(this, _publishedValueFallback);

		/// <summary>Static getter for Cache Length For Form Entries</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetConfigUmbracoFormCacheLength(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "configUmbracoFormCacheLength");

		///<summary>
		/// Select Form Entries Message Field: Name of the field that stores the Message in an Umbraco Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configUmbracoFormFieldMessage")]
		public virtual string ConfigUmbracoFormFieldMessage => GetConfigUmbracoFormFieldMessage(this, _publishedValueFallback);

		/// <summary>Static getter for Select Form Entries Message Field</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigUmbracoFormFieldMessage(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configUmbracoFormFieldMessage");

		///<summary>
		/// Select Form Entries Field Name: Name of the field that stores the Name in an Umbraco Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configUmbracoFormFieldName")]
		public virtual string ConfigUmbracoFormFieldName => GetConfigUmbracoFormFieldName(this, _publishedValueFallback);

		/// <summary>Static getter for Select Form Entries Field Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigUmbracoFormFieldName(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configUmbracoFormFieldName");

		///<summary>
		/// Default Select Form Entries Field Name: Text displayed when a user doesn't fill in their Name field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("configUmbracoFormFieldNameDefault")]
		public virtual string ConfigUmbracoFormFieldNameDefault => GetConfigUmbracoFormFieldNameDefault(this, _publishedValueFallback);

		/// <summary>Static getter for Default Select Form Entries Field Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetConfigUmbracoFormFieldNameDefault(IDomainConfigurationTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "configUmbracoFormFieldNameDefault");
	}
}
