//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Categories Settings</summary>
	[PublishedModel("editorCategoriesPrimarySettings")]
	public partial class EditorCategoriesPrimarySettings : PublishedElementModel, IEditorBackgroundSettings, IEditorBorderSettings, IEditorCategoriesBaseSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorCategoriesPrimarySettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorCategoriesPrimarySettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorCategoriesPrimarySettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Override Colours: OR Set the background to your own specific colour, image or gradient. If set will override current Subtheme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overrideColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel OverrideColor => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetOverrideColor(this, _publishedValueFallback);

		///<summary>
		/// Subtheme: Change subtheme for this item. Inherit = Use same subtheme as page 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subtheme")]
		public virtual string Subtheme => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Shade: Change section to dark or light mode. Inherit = Use whichever mode the page has
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("themeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades ThemeShade => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Border Color: Select color for border
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("borderColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor BorderColor => global::Protenacity.Cake.Web.Core.Constitution.EditorBorderSettings.GetBorderColor(this, _publishedValueFallback);

		///<summary>
		/// Border Edges: Which edges do you wish the border to be displayed on. Select all 4 options to complete the border
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("borderEdges")]
		public virtual global::System.Collections.Generic.IEnumerable<string> BorderEdges => global::Protenacity.Cake.Web.Core.Constitution.EditorBorderSettings.GetBorderEdges(this, _publishedValueFallback);

		///<summary>
		/// Placement: Where to place Headings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("placement")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorTabStripPlacements Placement => global::Protenacity.Cake.Web.Core.Constitution.EditorCategoriesBaseSettings.GetPlacement(this, _publishedValueFallback);

		///<summary>
		/// Show Separator: Use a separator between the different catagories
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("separator")]
		public virtual bool Separator => global::Protenacity.Cake.Web.Core.Constitution.EditorCategoriesBaseSettings.GetSeparator(this, _publishedValueFallback);

		///<summary>
		/// Show Heading Description: Show Heading Description for each selected heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("showHeadingDescription")]
		public virtual bool ShowHeadingDescription => global::Protenacity.Cake.Web.Core.Constitution.EditorCategoriesBaseSettings.GetShowHeadingDescription(this, _publishedValueFallback);
	}
}
