//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Venue Opening Times</summary>
	[PublishedModel("editorOpeningTimesPrimary")]
	public partial class EditorOpeningTimesPrimary : PublishedElementModel, IEditorBlockPrimary, IEditorOpeningTimesEmbedded
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorOpeningTimesPrimary";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorOpeningTimesPrimary, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorOpeningTimesPrimary(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Enable: Should this section display?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("enable")]
		public virtual bool Enable => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetEnable(this, _publishedValueFallback);

		///<summary>
		/// Identifier: {span title="Also used as id for block for anchoring (Text convert to all lowercase, spaces are turned into dashes)"}Internal moniker{/span}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("identifier")]
		public virtual string Identifier => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetIdentifier(this, _publishedValueFallback);

		///<summary>
		/// Section Link: Optional link for more information about this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link MainLink => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetMainLink(this, _publishedValueFallback);

		///<summary>
		/// Section Title: Optional &lt;h2&gt; title placed above block
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainTitle")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString MainTitle => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetMainTitle(this, _publishedValueFallback);

		///<summary>
		/// Footer: Text placed below opening times
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footer")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Footer => global::Protenacity.Cake.Web.Core.Constitution.EditorOpeningTimesEmbedded.GetFooter(this, _publishedValueFallback);

		///<summary>
		/// Header: Header for Opening Times
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("header")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Header => global::Protenacity.Cake.Web.Core.Constitution.EditorOpeningTimesEmbedded.GetHeader(this, _publishedValueFallback);

		///<summary>
		/// Text: Text placed above the opening times
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("text")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Text => global::Protenacity.Cake.Web.Core.Constitution.EditorOpeningTimesEmbedded.GetText(this, _publishedValueFallback);

		///<summary>
		/// Times: Enter start and end time for when the venue is open. If the venue closes in middle of the day, then create a start and end timeslot for the morning and create a separate timeslot with its own start and end time for the afternoon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("times")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Times => global::Protenacity.Cake.Web.Core.Constitution.EditorOpeningTimesEmbedded.GetTimes(this, _publishedValueFallback);
	}
}
