//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Web Pages Settings</summary>
	[PublishedModel("editorSelectNodesSettings")]
	public partial class EditorSelectNodesSettings : PublishedElementModel, IEditorActionEmbeddedSettings, IEditorBackgroundSettings, IEditorBorderSettings, IEditorCardBaseSettings, IEditorOrderSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorSelectNodesSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorSelectNodesSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorSelectNodesSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Action Style: Display as a button or underlined text with optional icon  Button = Uses current theme to colour button. Link = Hyperlink using current theme to colour link. Link with Icon = Hyperlink with icon using current theme. Header = Makes the header of the card the hyperlink. Hide = No clickable action. Button (Primary) = Blue button Button (Secondary) = Grey button Button (Success) = Green button Button (Danger) = Red button Button (Warning) = Yellow button Button (Info) = Cyan button Button (Light) = White button Button (Dark) = Black button 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleAction")]
		public virtual string StyleAction => global::Protenacity.Cake.Web.Core.Constitution.EditorActionEmbeddedSettings.GetStyleAction(this, _publishedValueFallback);

		///<summary>
		/// Action Alignment: Location of Button or Link. Absolute = Will position over the top of other items (if applicable). Relative = Will try and make other items flow around it (if applicable).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("styleActionAlignment")]
		public virtual global::Protenacity.Cake.Web.Core.Property.ActionStyleAlignments StyleActionAlignment => global::Protenacity.Cake.Web.Core.Constitution.EditorActionEmbeddedSettings.GetStyleActionAlignment(this, _publishedValueFallback);

		///<summary>
		/// Action Click Area: Which area that can clicked
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleActionClickArea")]
		public virtual string StyleActionClickArea => global::Protenacity.Cake.Web.Core.Constitution.EditorActionEmbeddedSettings.GetStyleActionClickArea(this, _publishedValueFallback);

		///<summary>
		/// Override Colours: OR Set the background to your own specific colour, image or gradient. If set will override current Subtheme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overrideColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel OverrideColor => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetOverrideColor(this, _publishedValueFallback);

		///<summary>
		/// Subtheme: Change subtheme for this item. Inherit = Use same subtheme as page 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subtheme")]
		public virtual string Subtheme => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Shade: Change section to dark or light mode. Inherit = Use whichever mode the page has
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("themeShade")]
		public virtual string ThemeShade => global::Protenacity.Cake.Web.Core.Constitution.EditorBackgroundSettings.GetThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Border Color: Select color for border
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("borderColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor BorderColor => global::Protenacity.Cake.Web.Core.Constitution.EditorBorderSettings.GetBorderColor(this, _publishedValueFallback);

		///<summary>
		/// Border Edges: Which edges do you wish the border to be displayed on. Select all 4 options to complete the border
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("borderEdges")]
		public virtual global::System.Collections.Generic.IEnumerable<string> BorderEdges => global::Protenacity.Cake.Web.Core.Constitution.EditorBorderSettings.GetBorderEdges(this, _publishedValueFallback);

		///<summary>
		/// Show Click Arrow: Show a click arror aligned to the right, giving an indication that clicking this card will provide an event. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("showClickArrow")]
		public virtual bool ShowClickArrow => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetShowClickArrow(this, _publishedValueFallback);

		///<summary>
		/// Date: Do we show the Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleDate")]
		public virtual string StyleDate => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleDate(this, _publishedValueFallback);

		///<summary>
		/// Header: Do we show the Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleHeader")]
		public virtual string StyleHeader => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleHeader(this, _publishedValueFallback);

		///<summary>
		/// Image Location: Where to place the image in relations to the other elements
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleImage")]
		public virtual string StyleImage => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleImage(this, _publishedValueFallback);

		///<summary>
		/// Image Size: How to size image compared to rest of the card information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleImageSize")]
		public virtual string StyleImageSize => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleImageSize(this, _publishedValueFallback);

		///<summary>
		/// Text: Do we show the Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleText")]
		public virtual string StyleText => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleText(this, _publishedValueFallback);

		///<summary>
		/// Time: Do we show the Time
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("styleTime")]
		public virtual string StyleTime => global::Protenacity.Cake.Web.Core.Constitution.EditorCardBaseSettings.GetStyleTime(this, _publishedValueFallback);

		///<summary>
		/// Order: Order of items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("order")]
		public virtual string Order => global::Protenacity.Cake.Web.Core.Constitution.EditorOrderSettings.GetOrder(this, _publishedValueFallback);
	}
}
