//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Full Size Map</summary>
	[PublishedModel("editorMapPrimary")]
	public partial class EditorMapPrimary : PublishedElementModel, IEditorBlockPrimary, IEditorMapBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorMapPrimary";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorMapPrimary, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorMapPrimary(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Enable: Should this section display?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("enable")]
		public virtual bool Enable => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetEnable(this, _publishedValueFallback);

		///<summary>
		/// Identifier: {span title="Also used as id for block for anchoring (Text convert to all lowercase, spaces are turned into dashes)"}Internal moniker{/span}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("identifier")]
		public virtual string Identifier => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetIdentifier(this, _publishedValueFallback);

		///<summary>
		/// Section Link: Optional link for more information about this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link MainLink => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetMainLink(this, _publishedValueFallback);

		///<summary>
		/// Section Title: Optional &lt;h2&gt; title placed above block
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainTitle")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString MainTitle => global::Protenacity.Cake.Web.Core.Constitution.EditorBlockPrimary.GetMainTitle(this, _publishedValueFallback);

		///<summary>
		/// Location: Pick a location on Earth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapLocation")]
		public virtual global::Protenacity.Web.OpenStreetMap.Core.Map MapLocation => global::Protenacity.Cake.Web.Core.Constitution.EditorMapBase.GetMapLocation(this, _publishedValueFallback);

		///<summary>
		/// Name: If Map is Region type, then is used to set Region shown otherwise optional Name for location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapName")]
		public virtual string MapName => global::Protenacity.Cake.Web.Core.Constitution.EditorMapBase.GetMapName(this, _publishedValueFallback);

		///<summary>
		/// Type: For map types other than Region, sets the pin, view and zoom level of map. For Region map set the region required in Name field below   
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapType")]
		public virtual string MapType => global::Protenacity.Cake.Web.Core.Constitution.EditorMapBase.GetMapType(this, _publishedValueFallback);
	}
}
