//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "editorExpandableSectionBaseSettings"
	/// <summary>Expandable Section Base Settings</summary>
	public partial interface IEditorExpandableSectionBaseSettings : IPublishedElement
	{
		/// <summary>Collapsed Size Unit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string CollapsedSizeUnit { get; }

		/// <summary>Collapsed Size Value</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		int CollapsedSizeValue { get; }

		/// <summary>Expand Collapse Method</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ExpandCollapseMethod { get; }

		/// <summary>Intial State</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string InitialState { get; }
	}

	/// <summary>Expandable Section Base Settings</summary>
	[PublishedModel("editorExpandableSectionBaseSettings")]
	public partial class EditorExpandableSectionBaseSettings : PublishedElementModel, IEditorExpandableSectionBaseSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorExpandableSectionBaseSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorExpandableSectionBaseSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorExpandableSectionBaseSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Collapsed Size Unit: Screen Percentage = How much of the screen in percentage should be taken up by this section when section is in collapsed mode. Valid numbers are from 0 for invisible, to 100 the total screen size. The section height can be larger than the screen size.  Section Height = How much of the section should we display when in collapsed mode. Valid numbers are 0 for invisible to 100 the total section size which effectively negates the purpose of this section.  Fixed Height = Height in font units of em where 1 = height of normal font. Valid number are from 0 for invisible to the total section height as measured in font heights.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("collapsedSizeUnit")]
		public virtual string CollapsedSizeUnit => GetCollapsedSizeUnit(this, _publishedValueFallback);

		/// <summary>Static getter for Collapsed Size Unit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetCollapsedSizeUnit(IEditorExpandableSectionBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "collapsedSizeUnit");

		///<summary>
		/// Collapsed Size Value: Value for Collapsed Size. What this value means depends on what the Unit is.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("collapsedSizeValue")]
		public virtual int CollapsedSizeValue => GetCollapsedSizeValue(this, _publishedValueFallback);

		/// <summary>Static getter for Collapsed Size Value</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static int GetCollapsedSizeValue(IEditorExpandableSectionBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "collapsedSizeValue");

		///<summary>
		/// Expand Collapse Method: How does the user expand and collapse this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("expandCollapseMethod")]
		public virtual string ExpandCollapseMethod => GetExpandCollapseMethod(this, _publishedValueFallback);

		/// <summary>Static getter for Expand Collapse Method</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetExpandCollapseMethod(IEditorExpandableSectionBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "expandCollapseMethod");

		///<summary>
		/// Intial State
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("initialState")]
		public virtual string InitialState => GetInitialState(this, _publishedValueFallback);

		/// <summary>Static getter for Intial State</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetInitialState(IEditorExpandableSectionBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "initialState");
	}
}
