//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Editor Page</summary>
	[PublishedModel("editorPage")]
	public partial class EditorPage : PublishedContentModel, IAlertTab, IAsideTab, IBannerTab, ICategoriesTab, IContentTab, IFurnitureTab, IPageTitleTab, ISeoTab, ISubfooterTab, IThemeTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "editorPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Status: {b}Inherit{/b} alert bar status from parent web page or {b}show{/b}/{b}hide{/b} this alert bar 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("alertStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.AlertStatuses AlertStatus => global::Protenacity.Cake.Web.Core.Constitution.AlertTab.GetAlertStatus(this, _publishedValueFallback);

		///<summary>
		/// Text: Text to be displayed when this alert is enabled
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("alertText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AlertText => global::Protenacity.Cake.Web.Core.Constitution.AlertTab.GetAlertText(this, _publishedValueFallback);

		///<summary>
		/// Title: Title for alert. Only displays when enabled
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("alertTitle")]
		public virtual string AlertTitle => global::Protenacity.Cake.Web.Core.Constitution.AlertTab.GetAlertTitle(this, _publishedValueFallback);

		///<summary>
		/// Type: What type of alert is this
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("alertType")]
		public virtual global::Protenacity.Cake.Web.Core.Property.AlertTypes AlertType => global::Protenacity.Cake.Web.Core.Constitution.AlertTab.GetAlertType(this, _publishedValueFallback);

		///<summary>
		/// Contents: List of links to place to the side of main content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("asideContent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel AsideContent => global::Protenacity.Cake.Web.Core.Constitution.AsideTab.GetAsideContent(this, _publishedValueFallback);

		///<summary>
		/// Fixed: True = Side panel is fixed in location and doesn't move when page is scrolled OR  False = Side panel scrolls with rest of page 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("asideFixed")]
		public virtual bool AsideFixed => global::Protenacity.Cake.Web.Core.Constitution.AsideTab.GetAsideFixed(this, _publishedValueFallback);

		///<summary>
		/// Offset: The side panel can be anchored beside which content block. 1 = Start beside the first main content block. 2 = Start beside the second main content block, which means the first content block will expand to take up all the available space. 3 = Start beside the third main content block, allowing the first and second main content block to expand.  
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("asideOffset")]
		public virtual decimal AsideOffset => global::Protenacity.Cake.Web.Core.Constitution.AsideTab.GetAsideOffset(this, _publishedValueFallback);

		///<summary>
		/// Status: Either {b}inherit{/b} side panel from parent web page, {b}hide{/b} side panel and allow web page content to be full width or display a side panel using the contents below on the {b}left{/b} or {b}right{/b} hand side of page. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("asideStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.AsideStatuses AsideStatus => global::Protenacity.Cake.Web.Core.Constitution.AsideTab.GetAsideStatus(this, _publishedValueFallback);

		///<summary>
		/// Hero Banners: Enter one or more slide that are positioned above page content 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannerContent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel BannerContent => global::Protenacity.Cake.Web.Core.Constitution.BannerTab.GetBannerContent(this, _publishedValueFallback);

		///<summary>
		/// Single Image: Single Image, that won't be resized and will be displayed in the ratio of the original.  Use with caution as large image will not be shrunk for small devices and can cause delays in displaying for those with limited bandwidth.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannerHeroImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BannerHeroImage => global::Protenacity.Cake.Web.Core.Constitution.BannerTab.GetBannerHeroImage(this, _publishedValueFallback);

		///<summary>
		/// Status: {b}Inherit{/b} Hero Banner from parent page or {b}Show Hero Banners{/b}, {b}Show Single Image{/b} or {b}Hide{/b} Hero Banner from information entered below 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("bannerStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.BannerStatuses BannerStatus => global::Protenacity.Cake.Web.Core.Constitution.BannerTab.GetBannerStatus(this, _publishedValueFallback);

		///<summary>
		/// Categories: Select which categories, if any, this page is associated with.   Only pages that have Seo Enabled will be included in Category results. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("categories")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Categories => global::Protenacity.Cake.Web.Core.Constitution.CategoriesTab.GetCategories(this, _publishedValueFallback);

		///<summary>
		/// Body: Main contents of Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("body")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Body => global::Protenacity.Cake.Web.Core.Constitution.ContentTab.GetBody(this, _publishedValueFallback);

		///<summary>
		/// Override Breadcrumbs Colours: Set custom colours for Breadcrumbs. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureBreadcrumbsColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureBreadcrumbsColor => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureBreadcrumbsColor(this, _publishedValueFallback);

		///<summary>
		/// Breadcrumb Status: Should this Breadcrumb be shown, hidden or inherit it's status from its parent page. Always hidden on Home Page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureBreadcrumbStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.BreadcrumbStatuses FurnitureBreadcrumbStatus => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureBreadcrumbStatus(this, _publishedValueFallback);

		///<summary>
		/// Breadcrumb Subtheme: Set the subtheme for the Breadcrumb.  Only valid if Breadcrumb is being displayed
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureBreadcrumbSubtheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorSubthemes FurnitureBreadcrumbSubtheme => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureBreadcrumbSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Breadcrumb Shade: Shade of Breadcrumb.  Only valid if Breadcrumb is being shown
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureBreadcrumbThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureBreadcrumbThemeShade => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureBreadcrumbThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Override Footer Colours: Set custom colours for Footer. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterColor => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterColor(this, _publishedValueFallback);

		///<summary>
		/// Footer Information: Area to place Copyright, address and other information about website.  {{year}} = Current Year
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterInformation")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterInformation => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterInformation(this, _publishedValueFallback);

		///<summary>
		/// Footer Menu: Optional Footer menu for microsite
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterMenu")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterMenu => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterMenu(this, _publishedValueFallback);

		///<summary>
		/// Footer Message: Main text for footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterMessage")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterMessage => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterMessage(this, _publishedValueFallback);

		///<summary>
		/// Footer Social Media Links: Links to your Social Media Feeds
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterSocialMediaLinks")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterSocialMediaLinks => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterSocialMediaLinks(this, _publishedValueFallback);

		///<summary>
		/// Footer Subtheme: Set subtheme for footer or Inherit Page subtheme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureFooterSubtheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorSubthemes FurnitureFooterSubtheme => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Footer Shade: Set light or dark shade for footer or inherit Page shade value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureFooterThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureFooterThemeShade => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureFooterThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Override Header Colours: Set custom colours for Header. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderColor => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderColor(this, _publishedValueFallback);

		///<summary>
		/// Header Menu: Optional Menu for micro-site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderMenu")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderMenu => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderMenu(this, _publishedValueFallback);

		///<summary>
		/// Header Menu Position: Where to place the Header menu on Larger devices like laptop or desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderMenuPosition")]
		public virtual global::Protenacity.Cake.Web.Core.Property.HeaderMenuPositions FurnitureHeaderMenuPosition => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderMenuPosition(this, _publishedValueFallback);

		///<summary>
		/// Header Stick to Top: Should the header stick to the top of the page and still be visible even when the user scrolls down
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderSticky")]
		public virtual bool FurnitureHeaderSticky => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderSticky(this, _publishedValueFallback);

		///<summary>
		/// Header Subtheme: Set subtheme for header or Inherit Page subtheme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderSubtheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorSubthemes FurnitureHeaderSubtheme => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Header Shade: Set light or dark shade for header or inherit Page shade value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureHeaderThemeShade => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureHeaderThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Logo: Logo image for micro-site, placed in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureLogoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FurnitureLogoImage => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureLogoImage(this, _publishedValueFallback);

		///<summary>
		/// Logo Size: Ratio of logo image in Width x Height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureLogoRatio")]
		public virtual global::Protenacity.Cake.Web.Core.Property.FurnitureLogoRatios FurnitureLogoRatio => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureLogoRatio(this, _publishedValueFallback);

		///<summary>
		/// Show All Services: Show All Services button in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowAllServices")]
		public virtual bool FurnitureShowAllServices => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureShowAllServices(this, _publishedValueFallback);

		///<summary>
		/// Show Header Menu on Larger Devices: Show standard menu in header section when being displayed on larger devices like laptop or desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowHeaderMenuOnLargerDevices")]
		public virtual bool FurnitureShowHeaderMenuOnLargerDevices => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureShowHeaderMenuOnLargerDevices(this, _publishedValueFallback);

		///<summary>
		/// Show Header Menu on Smaller Devices: Show hamburger menu in header section when being displayed on smaller devices like a phone or tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowHeaderMenuOnSmallerDevices")]
		public virtual bool FurnitureShowHeaderMenuOnSmallerDevices => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureShowHeaderMenuOnSmallerDevices(this, _publishedValueFallback);

		///<summary>
		/// Show Search Bar: Show search bar in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowSearchBar")]
		public virtual bool FurnitureShowSearchBar => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureShowSearchBar(this, _publishedValueFallback);

		///<summary>
		/// Status: {b}Inherit{/b} header & footer information from parent web page or {b}show{/b} header & footer information below
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.FurntitureStatuses FurnitureStatus => global::Protenacity.Cake.Web.Core.Constitution.FurnitureTab.GetFurnitureStatus(this, _publishedValueFallback);

		///<summary>
		/// Page Title: Main &lt;h1&gt; Header for page. Placed above all content 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleName")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageTitleName => global::Protenacity.Cake.Web.Core.Constitution.PageTitleTab.GetPageTitleName(this, _publishedValueFallback);

		///<summary>
		/// Promote Page Title: Give prominence to Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageTitlePromote")]
		public virtual bool PageTitlePromote => global::Protenacity.Cake.Web.Core.Constitution.PageTitleTab.GetPageTitlePromote(this, _publishedValueFallback);

		///<summary>
		/// Page Title Subtheme: Set a Subtheme for the page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageTitleSubtheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorSubthemes PageTitleSubtheme => global::Protenacity.Cake.Web.Core.Constitution.PageTitleTab.GetPageTitleSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Page Title Shade: Set a shade for the page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageTitleThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades PageTitleThemeShade => global::Protenacity.Cake.Web.Core.Constitution.PageTitleTab.GetPageTitleThemeShade(this, _publishedValueFallback);

		///<summary>
		/// Keywords: Most important words for search engines to notice on this page. Don't use same keywords across all pages.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Keywords => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetKeywords(this, _publishedValueFallback);

		///<summary>
		/// Abstract: Brief summary of this page, used whenever this page is linked from other sources and rich text can be used.  If blank will use Description instead.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoAbstract")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SeoAbstract => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoAbstract(this, _publishedValueFallback);

		///<summary>
		/// Canonical Url: The definitive Url for a specific piece of content when multiple Urls exist for that same content, preventing duplicate content issues for search engines.   Leave blank if this page is the definitive and/or source of original content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoCanonicalUrl")]
		public virtual global::Umbraco.Cms.Core.Models.Link SeoCanonicalUrl => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoCanonicalUrl(this, _publishedValueFallback);

		///<summary>
		/// Date Published: Select a date for when this page was originally published. If empty will use date this page was last updated
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("seoDatePublished")]
		public virtual global::System.DateTime SeoDatePublished => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoDatePublished(this, _publishedValueFallback);

		///<summary>
		/// Description: Brief summary of this page, used whenever this page is linked from other sources and only plain text can be used.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoDescription")]
		public virtual string SeoDescription => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoDescription(this, _publishedValueFallback);

		///<summary>
		/// Priority: How important is this web page compared to others web pages within this site. Search engines use this value to rank your pages with similar keywords/content. Setting all pages to the same value has no effect and is counter-productive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("seoPriority")]
		public virtual int SeoPriority => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoPriority(this, _publishedValueFallback);

		///<summary>
		/// Promoted Search Terms: Keywords that are promoted for our own search page  
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoPromotedSearchTerms")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SeoPromotedSearchTerms => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoPromotedSearchTerms(this, _publishedValueFallback);

		///<summary>
		/// Status: {b}Inherit{/b} index status from parent page or {b}enable{/b}/{b}disable{/b} this page from being able to be indexed by search engines like {a href="https://developers.google.com/search/docs/fundamentals/how-search-works"}Google{/a}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("seoStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.SeoStatuses SeoStatus => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoStatus(this, _publishedValueFallback);

		///<summary>
		/// Thumbnail: Image shown when linked from search engines like Google or from other pages within this site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoThumbnail")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SeoThumbnail => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoThumbnail(this, _publishedValueFallback);

		///<summary>
		/// Title: Title for page, if left blank will use name of page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Change Url: Override the default url name of this page 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetUmbracoUrlAlias(this, _publishedValueFallback);

		///<summary>
		/// Override Colours: Set override custom colours for Subfooter. If empty will use current Theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subfooterColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel SubfooterColor => global::Protenacity.Cake.Web.Core.Constitution.SubfooterTab.GetSubfooterColor(this, _publishedValueFallback);

		///<summary>
		/// Show Last Updated Date: Display the page's last updated date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("subfooterShowLastUpdatedDate")]
		public virtual bool SubfooterShowLastUpdatedDate => global::Protenacity.Cake.Web.Core.Constitution.SubfooterTab.GetSubfooterShowLastUpdatedDate(this, _publishedValueFallback);

		///<summary>
		/// Show Next Review Date: Show the next time this page needs reviewing. Only valid if page has a review date and is enabled for reviewing.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("subfooterShowNextReviewDate")]
		public virtual bool SubfooterShowNextReviewDate => global::Protenacity.Cake.Web.Core.Constitution.SubfooterTab.GetSubfooterShowNextReviewDate(this, _publishedValueFallback);

		///<summary>
		/// Show Return To Top Icon: Show an icon on bottom right hand of page that when pressed scrolls the page back to the top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("subfooterShowReturnToTopIcon")]
		public virtual bool SubfooterShowReturnToTopIcon => global::Protenacity.Cake.Web.Core.Constitution.SubfooterTab.GetSubfooterShowReturnToTopIcon(this, _publishedValueFallback);

		///<summary>
		/// Status: Either {b}inherit{/b} subfooter from parent web page or {b}show{/b}/{b}hide{/b} subfooter using information below
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("subfooterStatus")]
		public virtual global::Protenacity.Cake.Web.Core.Property.SubfooterStatuses SubfooterStatus => global::Protenacity.Cake.Web.Core.Constitution.SubfooterTab.GetSubfooterStatus(this, _publishedValueFallback);

		///<summary>
		/// Subtheme: Variant of theme. Inherit = Use same subtheme as parent page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageSubtheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorSubthemes PageSubtheme => global::Protenacity.Cake.Web.Core.Constitution.ThemeTab.GetPageSubtheme(this, _publishedValueFallback);

		///<summary>
		/// Theme: Theme for this page. Inherit = Use same theme as parent page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageTheme")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemes PageTheme => global::Protenacity.Cake.Web.Core.Constitution.ThemeTab.GetPageTheme(this, _publishedValueFallback);

		///<summary>
		/// Shade: Overall shade of page.  Inherit = Use same intensity as parent page. Light = Bright page with dark text. Dark = Dark page with light text.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("pageThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades PageThemeShade => global::Protenacity.Cake.Web.Core.Constitution.ThemeTab.GetPageThemeShade(this, _publishedValueFallback);
	}
}
