//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.2.2+11a412c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "editorRibbonBaseSettings"
	/// <summary>Ribbon Base Settings</summary>
	public partial interface IEditorRibbonBaseSettings : IPublishedElement
	{
		/// <summary>Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		bool Color { get; }

		/// <summary>Default Image Shape</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorBadgeImageShape> DefaultImageShape { get; }

		/// <summary>Image Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorCardStyleImageSizes> ImageSize { get; }
	}

	/// <summary>Ribbon Base Settings</summary>
	[PublishedModel("editorRibbonBaseSettings")]
	public partial class EditorRibbonBaseSettings : PublishedElementModel, IEditorRibbonBaseSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const string ModelTypeAlias = "editorRibbonBaseSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<EditorRibbonBaseSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public EditorRibbonBaseSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Color: True = Keep as a colour image or False = Use theme to gradient image 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("color")]
		public virtual bool Color => GetColor(this, _publishedValueFallback);

		/// <summary>Static getter for Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static bool GetColor(IEditorRibbonBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "color");

		///<summary>
		/// Default Image Shape: Default shape for Icons
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("defaultImageShape")]
		public virtual global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorBadgeImageShape> DefaultImageShape => GetDefaultImageShape(this, _publishedValueFallback);

		/// <summary>Static getter for Default Image Shape</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorBadgeImageShape> GetDefaultImageShape(IEditorRibbonBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorBadgeImageShape>>(publishedValueFallback, "defaultImageShape");

		///<summary>
		/// Image Size: How to size image compared to rest of the information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("imageSize")]
		public virtual global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorCardStyleImageSizes> ImageSize => GetImageSize(this, _publishedValueFallback);

		/// <summary>Static getter for Image Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorCardStyleImageSizes> GetImageSize(IEditorRibbonBaseSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorCardStyleImageSizes>>(publishedValueFallback, "imageSize");
	}
}
