//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "furnitureTab"
	/// <summary>Header & Footer Tab</summary>
	public partial interface IFurnitureTab : IPublishedElement
	{
		/// <summary>Override Breadcrumbs Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureBreadcrumbsColor { get; }

		/// <summary>Breadcrumb Status</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureBreadcrumbStatus { get; }

		/// <summary>Breadcrumb Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureBreadcrumbSubtheme { get; }

		/// <summary>Breadcrumb Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureBreadcrumbThemeShade { get; }

		/// <summary>Override Footer Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterColor { get; }

		/// <summary>Footer Information</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterInformation { get; }

		/// <summary>Footer Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterMenu { get; }

		/// <summary>Footer Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterMessage { get; }

		/// <summary>Footer Social Media Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterSocialMediaLinks { get; }

		/// <summary>Footer Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureFooterSubtheme { get; }

		/// <summary>Footer Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureFooterThemeShade { get; }

		/// <summary>Override Header Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderColor { get; }

		/// <summary>Header Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderMenu { get; }

		/// <summary>Header Menu Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureHeaderMenuPosition { get; }

		/// <summary>Header Stick to Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		bool FurnitureHeaderSticky { get; }

		/// <summary>Header Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureHeaderSubtheme { get; }

		/// <summary>Header Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureHeaderThemeShade { get; }

		/// <summary>Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops FurnitureLogoImage { get; }

		/// <summary>Logo Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		global::Protenacity.Cake.Web.Core.Property.FurnitureLogoRatios FurnitureLogoRatio { get; }

		/// <summary>Show All Services</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		bool FurnitureShowAllServices { get; }

		/// <summary>Show Header Menu on Larger Devices</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		bool FurnitureShowHeaderMenuOnLargerDevices { get; }

		/// <summary>Show Header Menu on Smaller Devices</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		bool FurnitureShowHeaderMenuOnSmallerDevices { get; }

		/// <summary>Show Search Bar</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		bool FurnitureShowSearchBar { get; }

		/// <summary>Status</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FurnitureStatus { get; }
	}

	/// <summary>Header & Footer Tab</summary>
	[PublishedModel("furnitureTab")]
	public partial class FurnitureTab : PublishedElementModel, IFurnitureTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "furnitureTab";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<FurnitureTab, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public FurnitureTab(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Override Breadcrumbs Colours: Set custom colours for Breadcrumbs. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureBreadcrumbsColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureBreadcrumbsColor => GetFurnitureBreadcrumbsColor(this, _publishedValueFallback);

		/// <summary>Static getter for Override Breadcrumbs Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureBreadcrumbsColor(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureBreadcrumbsColor");

		///<summary>
		/// Breadcrumb Status: Should this Breadcrumb be shown, hidden or inherit it's status from its parent page. Always hidden on Home Page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureBreadcrumbStatus")]
		public virtual string FurnitureBreadcrumbStatus => GetFurnitureBreadcrumbStatus(this, _publishedValueFallback);

		/// <summary>Static getter for Breadcrumb Status</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureBreadcrumbStatus(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureBreadcrumbStatus");

		///<summary>
		/// Breadcrumb Subtheme: Set the subtheme for the Breadcrumb.  Only valid if Breadcrumb is being displayed
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureBreadcrumbSubtheme")]
		public virtual string FurnitureBreadcrumbSubtheme => GetFurnitureBreadcrumbSubtheme(this, _publishedValueFallback);

		/// <summary>Static getter for Breadcrumb Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureBreadcrumbSubtheme(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureBreadcrumbSubtheme");

		///<summary>
		/// Breadcrumb Shade: Shade of Breadcrumb.  Only valid if Breadcrumb is being shown
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureBreadcrumbThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureBreadcrumbThemeShade => GetFurnitureBreadcrumbThemeShade(this, _publishedValueFallback);

		/// <summary>Static getter for Breadcrumb Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static global::Protenacity.Cake.Web.Core.Property.EditorThemeShades GetFurnitureBreadcrumbThemeShade(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades>(publishedValueFallback, "furnitureBreadcrumbThemeShade");

		///<summary>
		/// Override Footer Colours: Set custom colours for Footer. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterColor => GetFurnitureFooterColor(this, _publishedValueFallback);

		/// <summary>Static getter for Override Footer Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureFooterColor(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureFooterColor");

		///<summary>
		/// Footer Information: Area to place Copyright, address and other information about website.  {{year}} = Current Year
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterInformation")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterInformation => GetFurnitureFooterInformation(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Information</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetFurnitureFooterInformation(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "furnitureFooterInformation");

		///<summary>
		/// Footer Menu: Optional Footer menu for microsite
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterMenu")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterMenu => GetFurnitureFooterMenu(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureFooterMenu(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureFooterMenu");

		///<summary>
		/// Footer Message: Main text for footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterMessage")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FurnitureFooterMessage => GetFurnitureFooterMessage(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetFurnitureFooterMessage(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "furnitureFooterMessage");

		///<summary>
		/// Footer Social Media Links: Links to your Social Media Feeds
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterSocialMediaLinks")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureFooterSocialMediaLinks => GetFurnitureFooterSocialMediaLinks(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Social Media Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureFooterSocialMediaLinks(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureFooterSocialMediaLinks");

		///<summary>
		/// Footer Subtheme: Set subtheme for footer or Inherit Page subtheme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureFooterSubtheme")]
		public virtual string FurnitureFooterSubtheme => GetFurnitureFooterSubtheme(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureFooterSubtheme(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureFooterSubtheme");

		///<summary>
		/// Footer Shade: Set light or dark shade for footer or inherit Page shade value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureFooterThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureFooterThemeShade => GetFurnitureFooterThemeShade(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static global::Protenacity.Cake.Web.Core.Property.EditorThemeShades GetFurnitureFooterThemeShade(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades>(publishedValueFallback, "furnitureFooterThemeShade");

		///<summary>
		/// Override Header Colours: Set custom colours for Header. Leave empty to use default theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderColor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderColor => GetFurnitureHeaderColor(this, _publishedValueFallback);

		/// <summary>Static getter for Override Header Colours</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureHeaderColor(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureHeaderColor");

		///<summary>
		/// Header Menu: Optional Menu for micro-site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderMenu")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FurnitureHeaderMenu => GetFurnitureHeaderMenu(this, _publishedValueFallback);

		/// <summary>Static getter for Header Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GetFurnitureHeaderMenu(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(publishedValueFallback, "furnitureHeaderMenu");

		///<summary>
		/// Header Menu Position: Where to place the Header menu on Larger devices like laptop or desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderMenuPosition")]
		public virtual string FurnitureHeaderMenuPosition => GetFurnitureHeaderMenuPosition(this, _publishedValueFallback);

		/// <summary>Static getter for Header Menu Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureHeaderMenuPosition(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureHeaderMenuPosition");

		///<summary>
		/// Header Stick to Top: Should the header stick to the top of the page and still be visible even when the user scrolls down
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderSticky")]
		public virtual bool FurnitureHeaderSticky => GetFurnitureHeaderSticky(this, _publishedValueFallback);

		/// <summary>Static getter for Header Stick to Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static bool GetFurnitureHeaderSticky(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "furnitureHeaderSticky");

		///<summary>
		/// Header Subtheme: Set subtheme for header or Inherit Page subtheme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureHeaderSubtheme")]
		public virtual string FurnitureHeaderSubtheme => GetFurnitureHeaderSubtheme(this, _publishedValueFallback);

		/// <summary>Static getter for Header Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureHeaderSubtheme(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureHeaderSubtheme");

		///<summary>
		/// Header Shade: Set light or dark shade for header or inherit Page shade value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureHeaderThemeShade")]
		public virtual global::Protenacity.Cake.Web.Core.Property.EditorThemeShades FurnitureHeaderThemeShade => GetFurnitureHeaderThemeShade(this, _publishedValueFallback);

		/// <summary>Static getter for Header Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static global::Protenacity.Cake.Web.Core.Property.EditorThemeShades GetFurnitureHeaderThemeShade(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades>(publishedValueFallback, "furnitureHeaderThemeShade");

		///<summary>
		/// Logo: Logo image for micro-site, placed in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureLogoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FurnitureLogoImage => GetFurnitureLogoImage(this, _publishedValueFallback);

		/// <summary>Static getter for Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetFurnitureLogoImage(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "furnitureLogoImage");

		///<summary>
		/// Logo Size: Ratio of logo image in Width x Height
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureLogoRatio")]
		public virtual global::Protenacity.Cake.Web.Core.Property.FurnitureLogoRatios FurnitureLogoRatio => GetFurnitureLogoRatio(this, _publishedValueFallback);

		/// <summary>Static getter for Logo Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static global::Protenacity.Cake.Web.Core.Property.FurnitureLogoRatios GetFurnitureLogoRatio(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Protenacity.Cake.Web.Core.Property.FurnitureLogoRatios>(publishedValueFallback, "furnitureLogoRatio");

		///<summary>
		/// Show All Services: Show All Services button in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowAllServices")]
		public virtual bool FurnitureShowAllServices => GetFurnitureShowAllServices(this, _publishedValueFallback);

		/// <summary>Static getter for Show All Services</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static bool GetFurnitureShowAllServices(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "furnitureShowAllServices");

		///<summary>
		/// Show Header Menu on Larger Devices: Show standard menu in header section when being displayed on larger devices like laptop or desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowHeaderMenuOnLargerDevices")]
		public virtual bool FurnitureShowHeaderMenuOnLargerDevices => GetFurnitureShowHeaderMenuOnLargerDevices(this, _publishedValueFallback);

		/// <summary>Static getter for Show Header Menu on Larger Devices</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static bool GetFurnitureShowHeaderMenuOnLargerDevices(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "furnitureShowHeaderMenuOnLargerDevices");

		///<summary>
		/// Show Header Menu on Smaller Devices: Show hamburger menu in header section when being displayed on smaller devices like a phone or tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowHeaderMenuOnSmallerDevices")]
		public virtual bool FurnitureShowHeaderMenuOnSmallerDevices => GetFurnitureShowHeaderMenuOnSmallerDevices(this, _publishedValueFallback);

		/// <summary>Static getter for Show Header Menu on Smaller Devices</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static bool GetFurnitureShowHeaderMenuOnSmallerDevices(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "furnitureShowHeaderMenuOnSmallerDevices");

		///<summary>
		/// Show Search Bar: Show search bar in header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("furnitureShowSearchBar")]
		public virtual bool FurnitureShowSearchBar => GetFurnitureShowSearchBar(this, _publishedValueFallback);

		/// <summary>Static getter for Show Search Bar</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public static bool GetFurnitureShowSearchBar(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "furnitureShowSearchBar");

		///<summary>
		/// Status: {b}Inherit{/b} header & footer information from parent web page or {b}show{/b} header & footer information below
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("furnitureStatus")]
		public virtual string FurnitureStatus => GetFurnitureStatus(this, _publishedValueFallback);

		/// <summary>Static getter for Status</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFurnitureStatus(IFurnitureTab that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "furnitureStatus");
	}
}
