//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.2.2+11a412c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	// Mixin Content Type with alias "pageTitleTab"
	/// <summary>Page Title Tab</summary>
	public partial interface IPageTitleTab : IPublishedElement
	{
		/// <summary>Page Subtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageSubtitle { get; }

		/// <summary>Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageTitleName { get; }

		/// <summary>Promote Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		bool PageTitlePromote { get; }

		/// <summary>Page Title Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorSubthemes> PageTitleSubtheme { get; }

		/// <summary>Page Title Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades> PageTitleThemeShade { get; }
	}

	/// <summary>Page Title Tab</summary>
	[PublishedModel("pageTitleTab")]
	public partial class PageTitleTab : PublishedElementModel, IPageTitleTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const string ModelTypeAlias = "pageTitleTab";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<PageTitleTab, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public PageTitleTab(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Page Subtitle: &lt;h5&gt; placed just below Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSubtitle")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageSubtitle => GetPageSubtitle(this, _publishedValueFallback);

		/// <summary>Static getter for Page Subtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetPageSubtitle(IPageTitleTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "pageSubtitle");

		///<summary>
		/// Page Title: Main &lt;h1&gt; Header for page. Placed above all content 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleName")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageTitleName => GetPageTitleName(this, _publishedValueFallback);

		/// <summary>Static getter for Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetPageTitleName(IPageTitleTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "pageTitleName");

		///<summary>
		/// Promote Page Title: Give prominence to Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("pageTitlePromote")]
		public virtual bool PageTitlePromote => GetPageTitlePromote(this, _publishedValueFallback);

		/// <summary>Static getter for Promote Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static bool GetPageTitlePromote(IPageTitleTab that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "pageTitlePromote");

		///<summary>
		/// Page Title Subtheme: Set a Subtheme for the page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("pageTitleSubtheme")]
		public virtual global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorSubthemes> PageTitleSubtheme => GetPageTitleSubtheme(this, _publishedValueFallback);

		/// <summary>Static getter for Page Title Subtheme</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorSubthemes> GetPageTitleSubtheme(IPageTitleTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorSubthemes>>(publishedValueFallback, "pageTitleSubtheme");

		///<summary>
		/// Page Title Shade: Set a shade for the page title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		[ImplementPropertyType("pageTitleThemeShade")]
		public virtual global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades> PageTitleThemeShade => GetPageTitleThemeShade(this, _publishedValueFallback);

		/// <summary>Static getter for Page Title Shade</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.2+11a412c")]
		public static global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades> GetPageTitleThemeShade(IPageTitleTab that, IPublishedValueFallback publishedValueFallback) => that.Value<global::System.Nullable<global::Protenacity.Cake.Web.Core.Property.EditorThemeShades>>(publishedValueFallback, "pageTitleThemeShade");
	}
}
