//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.1.0+2832436
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Protenacity.Cake.Web.Core.Constitution
{
	/// <summary>Redirect Page</summary>
	[PublishedModel("redirectPage")]
	public partial class RedirectPage : PublishedContentModel, ISeoTab
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const string ModelTypeAlias = "redirectPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<RedirectPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public RedirectPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Page to Redirect To: Which page do you wish to redirect to.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirect")]
		public virtual global::Umbraco.Cms.Core.Models.Link Redirect => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "redirect");

		///<summary>
		/// Keywords: Most important words for search engines to notice on this page. Don't use same keywords across all pages.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("keywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Keywords => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetKeywords(this, _publishedValueFallback);

		///<summary>
		/// Abstract: Brief summary of this page, used whenever this page is linked from other sources and rich text can be used.  If blank will use Description instead.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoAbstract")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SeoAbstract => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoAbstract(this, _publishedValueFallback);

		///<summary>
		/// Canonical Url: The definitive Url for a specific piece of content when multiple Urls exist for that same content, preventing duplicate content issues for search engines.   Leave blank if this page is the definitive and/or source of original content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoCanonicalUrl")]
		public virtual global::Umbraco.Cms.Core.Models.Link SeoCanonicalUrl => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoCanonicalUrl(this, _publishedValueFallback);

		///<summary>
		/// Date Published: Select a date for when this page was originally published. If empty will use date this page was last updated
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("seoDatePublished")]
		public virtual global::System.DateTime SeoDatePublished => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoDatePublished(this, _publishedValueFallback);

		///<summary>
		/// Description: Brief summary of this page, used whenever this page is linked from other sources and only plain text can be used.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoDescription")]
		public virtual string SeoDescription => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoDescription(this, _publishedValueFallback);

		///<summary>
		/// Priority: How important is this web page compared to others web pages within this site. Search engines use this value to rank your pages with similar keywords/content. Setting all pages to the same value has no effect and is counter-productive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[ImplementPropertyType("seoPriority")]
		public virtual int SeoPriority => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoPriority(this, _publishedValueFallback);

		///<summary>
		/// Promoted Search Terms: Keywords that are promoted for our own search page  
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoPromotedSearchTerms")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SeoPromotedSearchTerms => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoPromotedSearchTerms(this, _publishedValueFallback);

		///<summary>
		/// Status: {b}Inherit{/b} index status from parent page or {b}enable{/b}/{b}disable{/b} this page from being able to be indexed by search engines like {a href="https://developers.google.com/search/docs/fundamentals/how-search-works"}Google{/a}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoStatus")]
		public virtual string SeoStatus => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoStatus(this, _publishedValueFallback);

		///<summary>
		/// Thumbnail: Image shown when linked from search engines like Google or from other pages within this site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoThumbnail")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SeoThumbnail => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetSeoThumbnail(this, _publishedValueFallback);

		///<summary>
		/// Title: Title for page, if left blank will use name of page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Change Url: Override the default url name of this page 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.1.0+2832436")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Protenacity.Cake.Web.Core.Constitution.SeoTab.GetUmbracoUrlAlias(this, _publishedValueFallback);
	}
}
